### ISSUE TITLE
Buran 1.8: Connection Error on app Startup

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#13]
I'm getting a Connection error screen when the app starts up:

![image](https://user-images.githubusercontent.com/4118560/169699561-4c1689a9-5a82-4911-8390-49d6e1fc608a.png)

This only happens if the app is not running, and you start it, as opposed to resuming it while already running.

Unfortunately issue #12 crashes the app completely, so when I start Buran again, I get this dialog

**Comment by Corewala** [comment]
Very strange. I'm getting this bug on my phone too, but not on the Android Studio emulator. This is going to be a bit difficult to debug.

**Comment by acidus99** [comment]
Perhaps some kind of out standing request? Its odd because it happens on start up. Perhaps you could have a state machine for this. No need to display this error dialog if there isn't a request in flight.

As an aside, the whole way connection errors are displayed could be improved. There is a disconnect between what I'm looking at and the error that gets display. For example, I've been looking at some gemtext, and I click a link to a capsule that is dead/timesout. The request is in flight, but taking to long, so I click the "back" button and navigate to another page or even capsule. 30-60 seconds later a connection error dialog appears about the link that I clicked and then "canceled" by going back.

**Comment by Corewala** [comment]
Yeah, the current system is pretty clunky. It's something I've been meaning to overhaul.

**Comment by marcdw1289** [comment]
The screenshot reminded me of a couple of capsules I have been unable to reach. Some of you know DistroTube. He made videos about Gemini yet I haven't been able to reach his capsule since last year. Same type of error. Not the only capsule but couldn't figure out the issue.
[ using OctoDroid so I can't post a shot ]

**Comment by Corewala** [comment]
This is a "connection refused" which implies that you are contacting an existing server, but that the server's network or the server itself is not configured to accept gemini requests.

**Comment by Corewala** [comment]
Alright so I think I fixed this (passed the "works on my phone" test), but due to the nature of the bug I have had some issues  properly testing the fix. I'm closing this issue, but please feel free to comment if it stays broken for you in the next release.
