### ISSUE TITLE
Buran 1.8: Flash of white screen during app startup

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#14]
This is an annoyance more than broken functionality. Buran 1.8 fixes the issue #3 which is great. I use the dark theme because I primarily use Buran at night before going to sleep.  Unfortunately, when the app starts (not when resuming) Burna displays an all-white screen for maybe a second before it then switches to using the dark theme. This is a surprise and kind of hurts my eyes.

This is especially prone to happen because of issues #12, which causes Buran to completely start more often

**Comment by Corewala** [comment]
Fixed
