### ISSUE TITLE
v1.7v/1.8 No internet connection, Android 7/8

### ISSUE THREAD

**Issue by marcdw1289** [Corewala/Buran#15]
Not sure this is related to any of the similar connection issues.

Hadn't updated my apps in a bit. My ROMs had Buran 1.6 (all good except dark theme never sticks). On both Nougat and Oreo, v1.8 produces a toast at the bottom that says "No internet connection". Not even allowed to tap into the address bar, keyboard will not show.
Uninstalled and tried v1.7. Same results. Version 1.6 is fine. Went back and forth between all three versions on both devices to verify behavior. Only 1.6 works.

Recorded a log but couldn't find any errors related to the app. Will check again and attach or haste.bin it.

Android 9 and 11, no issues with v1.8.

**Comment by Corewala** [comment]
The empty screen is a workaround to prevent crashes if Buran is launched with no internet access. Under normal circumstances, a refresh when internet access is available again should cause the app to load normally. This sounds like it must be an issue with the connectivityManager class in earlier APIs.

**Comment by Corewala** [comment]
I'll make the "no internet" blank screen a bit more responsive to prevent future confusion, but that doesn't look like it will fix your issue if it happens while internet access is available. Could you provide more information on the bug? I tried running the newest version of Buran on an Android Oreo emulator to test this bug, but everything looks to be working correctly.

**Comment by Corewala** [comment]
I'll close this issue for now, given as I can't replicate the bug. I will reopen this issue if you can provide further information in this thread.

**Comment by marcdw1289** [comment]
Many apologies. Been so busy with the job and a new Linux distro.

I discovered the problem I think. VPNs.
I have VPNs on all ROMs and in most cases InviZible Pro providing DNSCrypt and whatnot.

On Nougat and Oreo I turned off everything and rebooted. Buran 1.8 worked fine (despite an occasional 'Connection error' toast).
When I turned on the VPN (IVPN app on Nougat, OpenVPN on either) then v1.8 doesn't work (No internet connection).

So I tried a VPN that doesn't mess with IP addresses - TrackerControl.
On Oreo Buran worked. On Nougat, it did not.

I recorded a log but there were no errors or warnings regarding Buran but System.out shows the internet messages/status.

I can attach or link the log if so desired.
![20220528_045454](https://user-images.githubusercontent.com/42319182/170826119-52a889b0-31d8-4ceb-ac0f-0370f2f9f549.jpg)

**Comment by Corewala** [comment]
Oh I see. This is probably due to the fact that the function for getting internet access was reliant on specific connection modes, rather than just if any connection is available. I have simplified that function, so this will be fixed in the next update.
