### ISSUE TITLE
Headers without leading space don't render the first character

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#16]
Buran 1.8 (and probably earlier) is not properly rendering Header lines that don't use whitespace between the `#` and the header text. 

According to the [Gemtext spec](https://gitlab.com/gemini-specification/gemini-text/-/blob/master/specification.gmi), whitespace after the `#` in a header is optional:
> Lines beginning with "#" are heading lines.  Heading lines consist of one,
two or three consecutive "#" characters, followed by optional whitespace,
followed by heading text.

But saw this while browsing:

![image](https://user-images.githubusercontent.com/4118560/170828303-949df885-b0b0-4fa7-93f7-1a96f4aa3c77.png)
Here is the gemtext:
<pre>
#New things with the capsule
##New Hosting Provider
The ...
</pre>

gemini://tilde.team/~smokey/logs/2022-05-25-new-things.gmi

Looks like Buran is assuming there is whitespace after the '#' and skipping the first character of the text

**Comment by Corewala** [comment]
Huh. The adapter code was trying to cut off an additional character, despite calling "trim()" anyways. Fixed.
