### ISSUE TITLE
URL bar missing in right-to-left language

### ISSUE THREAD

**Issue by maemunman** [Corewala/Buran#17]
![Screenshot_۲۰۲۲۰۵۳۱-۱۰۵۸۳۸_Buran](https://user-images.githubusercontent.com/32847759/171254040-d64cad39-1a96-4db8-a447-75beeb6f0df4.jpg)

There is no URL there. I can go into settings>history and see the url, but I cannot modify it or paste a url.

**Comment by Corewala** [comment]
I'm going to try to fix this, but I don't speak any right-to-left languages, so I don't know the convention for text boxes. Should the addressbar be right-to-left or left-to-right?

**Comment by maemunman** [comment]
The contents of the url bar will always be primarily latin english letters, so left-to-right is probably the way to go there. If you're asking about where it should sit relative to the home and settings buttons, I think it would be, like this: `Settings < URL < Home`. But there's not really any rtl layout consistency among apps, so as long as it functions, it's good.

**Comment by Corewala** [comment]
Fixed. This will be in the next release, sorry about that.
