### ISSUE TITLE
Pubblish the app on the official f-droid repo

### ISSUE THREAD

**Issue by darhma** [Corewala/Buran#2]
I've discovered this app because it was added to the f-droid izzyondroid repository, I'm wondering if you would like to publish the app also in the official f-droid repo.
F-droid (https://f-droid.org/) is an alternative android app store that provides exclusively floss apps.

**Comment by Corewala** [comment]
Sorry for the long wait. I have filed an inclusion request [here](https://gitlab.com/fdroid/rfp/-/issues/2116).
