### ISSUE TITLE
Page crashes Buran v1.10

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#25]
(BTW, thanks for all the incredible bug fixes you have been doing recently! In the last few months Buran has become a very stable and enjoyable gemini client)

When I navigate to this URL in Buran v1.10, I get a hard crash. No message is displayed, the app just closes:
gemini://gem.pwarren.id.au/gemlog/2020-08-18.gmi

To help with testing, you can start on the following page. The first link causes the crash:
gemini://going-flying.com/~mernisse/11.gmi

**Comment by Corewala** [comment]
Well that's odd. When I try it on Buran, the capsule just loads for a while and then gives me a connection timeout popup. Same thing when I tried on a different client (Starfish). Could you provide more details on your network config if the crash still happens?

Thanks for reporting the bugs you find :)

**Comment by acidus99** [comment]
Nothing special with the network. Typical Wifi setup, using Buran on an Amazon Fire tablet.

**Comment by Corewala** [comment]
Revisiting this bug, I still haven't been able to replicate it, so I'm going to close this issue for now. Feel free to reply if you have any more information though!

**Comment by acidus99** [comment]
sounds good. I'll test again when you roll the next version of Buran. Thanks again for your great work
