### ISSUE TITLE
Buran incorrectly resolving Relative URLs with query strings

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#28]
I noticed a bug in present in both Buran v1.10 and v1.11.

Relative URLs that are just query strings are not properly resolved.  Consider I'm on page `gemini://gemi.dev/example` and it has a link line like this:
```
=> ?test test list
```
Clicking that should send a request for `gemini://gemi.dev/example?test` but instead it send a request for `gemini://gemi.dev/?test`

You can see an actual example with my Where in the World game: `gemini://gemi.dev/cgi-bin/witw.cgi/play`

Go to that page, then scroll down and click a link for a country. All those links are of the form:
```
=> ?,AF Afghanistan
```
So when you click Afghanistan the URL you should go to is `gemini://gemi.dev/cgi-bin/witw.cgi/play?,AF` but Buran is sending a request to `gemini://gemi.dev/cgi-bin/witw.cgi/?,AF`

**Comment by Corewala** [comment]
Fixed
