### ISSUE TITLE
Buran not using selected "dark" theme on startup

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#3]
When I first start Buran, it uses the light "theme" even though I have it configured to use the "dark" theme. I have to go into the settings screen, select a different theme, then select "dark" for it to use the dark theme again.

In the screen shot, you can see the "light" colored theme being used by the settings screen, despite the "Dark" theme being selected.

![IMG_4323](https://user-images.githubusercontent.com/4118560/162594603-406e1df6-879d-4e84-bbc1-c759173f49fd.jpg)

If I use another app, and swap back, the dark them is still in use. However if I'm running to many other applications, and switch back to Buran, it uses the light theme again. I assume Android is suspending/killing Buran, and then restarting it.

If it matters, I am using a Kindle Fire 7 9th Generation (running FireOS 7, which is based on Android 9)

**Comment by Corewala** [comment]
Fixed
