### ISSUE TITLE
Buran displaying same image for URL despite different query string

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#4]
I have a Gemini CGI that displays different images based on the query string. However Buran keeps displaying the same image, even though the query string has changed.

I run a Gemini mirror of the XKCD web comic. The comic number to display is passed via the query string. These 2 gemini links show different images in Elaho, Lagrange, and other Gemini clients

gemini://gemi.dev/cgi-bin/xkcd.cgi?55
gemini://gemi.dev/cgi-bin/xkcd.cgi?60

However Buran shows the same image for both. This same issue exists in Ariane as well.

If it matters, I am using a Kindle Fire 7 9th Generation (running FireOS 7, which is based on Android 9)

**Comment by Corewala** [comment]
Fixed
