### ISSUE TITLE
Excess './' in the url causes page to not load

### ISSUE THREAD

**Issue by bblhd** [Corewala/Buran#42]
When try to browse "gemini://compudanzas.net/" on Buran and open a link, the browser shows the loading animation and it doesn't stop.

When copying the address, links appear to have extra "./" inserted. For example "gemini://compudanzas.net/./jarotsim.gmi". After manually removing them, the page loads without error. Also, if I try to open a link multiple times, more "./" are inserted.

Bizarely, this issue only seems to affects compudanzas, other websites I've tried load perfectly fine, even if the "./" are manually added.

Steps to reproduce:
1. Go to "gemini://compudanzas.net/"
2. Open any gemini link.

**Comment by qespr** [comment]
I couldn't reproduce this in current source build, seems like this has been a redirection bug which is already fixed, just not updated on F-Droid.

**Comment by bblhd** [comment]
Ah, thanks for checking. Guess Ill close the issue and wait then :)
