### ISSUE TITLE
Feature Request: Different search engine options

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#6]
Right now Buran uses TLGS as its search engine and there is no way to change this.

TLGS is great, but I'd like to use Kennedy (gemini://kennedy.gemi.dev).

Suggestion 1: Provide a list of search engines the user can choose (TLGS, Kennedy, and Geminispace.info)
Suggestion 2: Allow users to define their own search engine: Most ask that you specify the URL to use for the search, and the search terms are sent as a query string on that URL. This is approach is great since a) you don't have to maintain a list of search engines and b) it allows users to add search for specific sites or CGI's that have popped up, such as the recipe search or the Wikipedia frontend.

**Comment by Corewala** [comment]
Search engine picking has been implemented, and will be available in the next release :)
