### ISSUE TITLE
Odd, repeatable, localhost connection error

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#9]
This is a really odd error, but it is consistent and repeatable. When attempting to load certain URLs, I will get this error message:

![image](https://user-images.githubusercontent.com/4118560/167876741-e77980d0-7d92-4e4e-a0dc-766ddcca9074.png)

This is odd for several reasons, so I will try to provide as much information as I can:
- I'm not making a request to `localhost`. I'm on a capsule (`gemi.dev`) and I'm clicking a link to that same capsule (as an example lets say `gemini://gemi.dev/example?foo`")
- Other URLs on that capsule are working fine (e.g. `gemini://gemi.dev/other-example` doesn't trigger the error), so I'm not sure why a "Connection Error" is happening. Clearly Buran can connect to the host and get responses.
- Clicking the same link over and over again generates the same error dialog, but the port number in the `from /;; (port X)` part of the error message increases by 6.
- This only happens on URLs with query strings
- Looking at my capsule logs, I can see that a request came in and I can see that a successful status code and body were returned to the client. Again, not sure why a "connection error" happens when the host is getting the request and return a response
- There is nothing weird or special about the returned content. Its a few thousand bytes of gemtext

I'm not sure if this will reproduce for you. I'm on the page:
`gemini://gemi.dev/cgi-bin/wp.cgi/view?f101`. Click thing the links for "F-101 Voodoo"  or "Dominican frigate" cause the error. Clicking on "General Electric F101" does not.

Like I said it's weird. It only happens on URLs with query strings. I have seen this happen on other capsules like search engines as well.

**Comment by Corewala** [comment]
Fixed! Took me a while to find the problem. The links which give the error don't need to have query strings. The issue is that they are returning local redirect headers which the request function was handling as global URIs with a empty hostnames.
